### ISSUE TITLE
Discord Community

### ISSUE THREAD

**Issue by psegovias** [imartinez/privateGPT#264] opened 2023-05-17 21:35 UTC
I hope I'm not breaking any rules with this, but I've created a discord for the community, where we can share experiences, advice and ideas, so we'll free up the Issue section a bit.

Soon I will be adding functionalities to the server, discord link: https://discord.gg/hrRWcuWaFb

Cheers!

**Comment by psegovias** [comment] 2023-05-17 21:41
@imartinez no hay problema con esto?

**Comment by imartinez** [comment] 2023-05-17 21:51
I set up the Discussions section trying to address the same problem: issues section being filled with questions. In my opinion Discord is less organized than GitHub Discussions; they added the "forum" functionality recently but it adds no value over using GitHub Discussions. Having said that, feel free to set up the discord. 

I'm closing this issue because it is not a bug or a feature request.

**Closed** 2023-05-17 21:51 UTC
