### ISSUE TITLE
Private GPT traceback issue

### ISSUE THREAD

**Issue by lkarpo57** [imartinez/privateGPT#874] opened 2023-07-20 16:51 UTC
Traceback (most recent call last):
  File "privateGPT.py", line 23, in <module>
    from constants import CHROMA_SETTINGS
  File "C:\Users\lkarpo\Downloads\privateGPT-main\privateGPT-main\constants.py", line 11, in <module>
    CHROMA_SETTINGS = Settings(
  File "pydantic\env_settings.py", line 40, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
persist_directory
  none is not an allowed value (type=type_error.none.not_allowed)

I made the change to 
if model_type == "LlamaCpp":
        llm = LlamaCpp(model_path=model_path, n_ctx=model_n_ctx, callbacks=callbacks, verbose=False)
    elif model_type == "GPT4All":
        llm = GPT4All(model=model_path, n_ctx=model_n_ctx, backend='gptj', callbacks=callbacks, verbose=False)
    else:
            print(f"Model {model_type} not supported!")
    exit;

but the error persists
is coming up when trying to run privategpt.py thru anaconda prompt.  has anyone else had this error?

**Comment by thebetauser** [comment] 2023-07-20 18:22
Duplicate of #865

**Closed** 2024-02-07 11:43 UTC
Labels: bug, primordial
