### ISSUE TITLE
line 97, in data_gym_to_mergeable_bpe_ranks     assert bpe_ranks == encoder_json_loaded

### ISSUE THREAD

**Issue by Imran-liaqat** [imartinez/privateGPT#1340] opened 2023-11-30 13:42 UTC
PS D:\Private_GPT\privateGPT>  poetry run  python .\private_gpt\main.py
Traceback (most recent call last):
  File "D:\Private_GPT\privateGPT\private_gpt\main.py", line 3, in <module>
    import llama_index
  File "C:\Users\Falcon\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-lpGZwSAi-py3.11\Lib\site-packages\llama_index\__init__.py", line 21, in <module>
    from llama_index.indices import (
  File "C:\Users\Falcon\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-lpGZwSAi-py3.11\Lib\site-packages\llama_index\indices\__init__.py", line 4, in <module>
    from llama_index.indices.composability.graph import ComposableGraph
  File "C:\Users\Falcon\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-lpGZwSAi-py3.11\Lib\site-packages\llama_index\indices\composability\__init__.py", line 4, in <module>
    from llama_index.indices.composability.graph import ComposableGraph
  File "C:\Users\Falcon\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-lpGZwSAi-py3.11\Lib\site-packages\llama_index\indices\composability\graph.py", line 7, in <module>
    from llama_index.indices.base import BaseIndex
  File "C:\Users\Falcon\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-lpGZwSAi-py3.11\Lib\site-packages\llama_index\indices\base.py", line 6, in <module>
    from llama_index.chat_engine.types import BaseChatEngine, ChatMode
  File "C:\Users\Falcon\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-lpGZwSAi-py3.11\Lib\site-packages\llama_index\chat_engine\__init__.py", line 1, in <module>
    from llama_index.chat_engine.condense_question import CondenseQuestionChatEngine
  File "C:\Users\Falcon\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-lpGZwSAi-py3.11\Lib\site-packages\llama_index\chat_engine\condense_question.py", line 6, in <module>
    from llama_index.chat_engine.types import (
  File "C:\Users\Falcon\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-lpGZwSAi-py3.11\Lib\site-packages\llama_index\chat_engine\types.py", line 11, in <module>
    from llama_index.memory import BaseMemory
  File "C:\Users\Falcon\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-lpGZwSAi-py3.11\Lib\site-packages\llama_index\memory\__init__.py", line 1, in <module>
    from llama_index.memory.chat_memory_buffer import ChatMemoryBuffer
  File "C:\Users\Falcon\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-lpGZwSAi-py3.11\Lib\site-packages\llama_index\memory\chat_memory_buffer.py", line 12, in <module>
    class ChatMemoryBuffer(BaseMemory):
  File "C:\Users\Falcon\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-lpGZwSAi-py3.11\Lib\site-packages\llama_index\memory\chat_memory_buffer.py", line 18, in ChatMemoryBuffer
    default_factory=cast(Callable[[], Any], GlobalsHelper().tokenizer),
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Falcon\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-lpGZwSAi-py3.11\Lib\site-packages\llama_index\utils.py", line 55, in tokenizer
    enc = tiktoken.get_encoding("gpt2")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Falcon\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-lpGZwSAi-py3.11\Lib\site-packages\tiktoken\registry.py", line 73, in get_encoding
    enc = Encoding(**constructor())
                     ^^^^^^^^^^^^^
  File "C:\Users\Falcon\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-lpGZwSAi-py3.11\Lib\site-packages\tiktoken_ext\openai_public.py", line 11, in gpt2
    mergeable_ranks = data_gym_to_mergeable_bpe_ranks(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Falcon\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-lpGZwSAi-py3.11\Lib\site-packages\tiktoken\load.py", line 97, in data_gym_to_mergeable_bpe_ranks
    assert bpe_ranks == encoder_json_loaded
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by lopagela** [comment] 2023-12-03 13:43
No context provided, and the project is not started as intended.
I'm suggesting to read the documentation, as suggested in the README.md: https://docs.privategpt.dev/

Closing this issue.

**Closed as completed by lopagela** 2023-12-03 13:43 UTC
