### ISSUE TITLE
Error: BaseSettings has been moved to the `pydantic-settings` 

### ISSUE THREAD

**Issue by soumyamaity** [imartinez/privateGPT#1004] opened 2023-09-01 20:43 UTC
**Describe the bug and how to reproduce it**
Unable to execute ingest.py
Throws the following error,

Traceback (most recent call last):
  File "/home/maity/aichat/privateGPT/ingest.py", line 32, in <module>
    from constants import CHROMA_SETTINGS
  File "/home/maity/aichat/privateGPT/constants.py", line 3, in <module>
    from chromadb.config import Settings
  File "/home/maity/.local/lib/python3.8/site-packages/chromadb/__init__.py", line 4, in <module>
    import chromadb.config
  File "/home/maity/.local/lib/python3.8/site-packages/chromadb/config.py", line 12, in <module>
    from pydantic import BaseSettings, validator
  File "/home/maity/.local/lib/python3.8/site-packages/pydantic/__init__.py", line 210, in __getattr__
    return _getattr_migration(attr_name)
  File "/home/maity/.local/lib/python3.8/site-packages/pydantic/_migration.py", line 289, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.3/migration/#basesettings-has-moved-to-pydantic-settings for more details.

**Environment (please complete the following information):**
 - OS / hardware: Ubuntu 20
 - Python version : 3.9

**Comment by ryanf789** [comment] 2023-09-04 04:07
I have the same issue

**Comment by yoskoslowich** [comment] 2023-09-05 17:12
This error stopped after I installed the dependencies with poetry

**Comment by soumyamaity** [comment] 2023-09-05 18:39
Issue was with the version of the pydantic. It  got resolved by removing all the packages and reinstall from requirements.txt
Use Python version 3.10

**Comment by joegsuero** [comment] 2023-09-19 20:30
The problem is that in the more recent versions **BaseSettings** it´s no longer imported from _**pydantic**_.

Instead import it from _**pydantic_settings**_

**Comment by eddietaylor** [comment] 2023-09-21 16:55
any idea when this change will be integrated?

**Closed** 2024-02-07 11:42 UTC
Labels: bug, primordial
