### ISSUE TITLE
Weaviate support

### ISSUE THREAD

**Issue by guyguy333** [imartinez/privateGPT#511] opened 2023-05-28 12:45 UTC
**Is your feature request related to a problem? Please describe.**

Deploying Chroma in a cloud native way is not so easy. Currently, there is a lack of support.

**Describe the solution you'd like**

Add support for Weaviate as an alternative to Chroma. Weaviate is much more mature for deployment, HA, ...

**Describe alternatives you've considered**

None

**Additional context**

**Comment by bobvanluijt** [comment] 2023-05-29 19:21
cc: @hsm207

**Comment by hsm207** [comment] 2023-05-29 20:31
@guyguy333 @bobvanluijt i think this should be closed as it is a duplicate of #147

**Comment by guyguy333** [comment] 2023-05-29 20:34
You're right, I missed that. Thanks. 

I hope your PR could be merged soon 🤞

**Closed** 2023-05-29 20:34 UTC
Labels: enhancement
